#!/bin/sh /etc/rc.common
#
# Copyright (c) 2017 Qualcomm Technologies, Inc.
#
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.

START=42

USE_PROCD=1

start_diag_app()
{
	local serverip=$(nvram get serverip)
	procd_open_instance
	if [ -n "$serverip" ]; then
		procd_set_param command  /usr/sbin/diag_socket_app -a "$serverip"
	else
		procd_set_param command /usr/sbin/diag_socket_app -a 192.168.31.100
	fi
	procd_set_param respawn
	procd_close_instance
	echo "/usr/sbin/diag_socket_app started" > /dev/kmsg
}

start_service() {
	is_ftm=$(cat /proc/xiaoqiang/ft_mode)
	[ "$is_ftm" = "1" ] && start_diag_app
}

