#!/bin/sh

PLUGINS_ROOT='/userdisk/appdata'


plugin_firewall_init() {
    iptables -t filter -w -S plugin_INPUT &>/dev/null && return

    iptables-restore --noflush <<EOF
*nat
:plugin_INPUT - [0:0]
:plugin_OUTPUT - [0:0]
:plugin_POSTROUTING - [0:0]
:plugin_PREROUTING - [0:0]
-I PREROUTING -j plugin_PREROUTING
-I INPUT -j plugin_INPUT
-I OUTPUT -j plugin_OUTPUT
-I POSTROUTING -j plugin_POSTROUTING
COMMIT
*mangle
:plugin_FORWARD - [0:0]
:plugin_INPUT - [0:0]
:plugin_OUTPUT - [0:0]
:plugin_POSTROUTING - [0:0]
:plugin_PREROUTING - [0:0]
-I PREROUTING -j plugin_PREROUTING
-I INPUT -j plugin_INPUT
-I FORWARD -j plugin_FORWARD
-I OUTPUT -j plugin_OUTPUT
-I POSTROUTING -j plugin_POSTROUTING
COMMIT
*filter
:plugin_FORWARD - [0:0]
:plugin_INPUT - [0:0]
:plugin_OUTPUT - [0:0]
-I INPUT -j plugin_INPUT
-I FORWARD -j plugin_FORWARD
-I OUTPUT -j plugin_OUTPUT
COMMIT
EOF
    return
}

plugin_firewall_reload() {
    if [ -d "$PLUGINS_ROOT" ]; then
        find "$PLUGINS_ROOT" -type f -name "firewall.sh" -exec sh -c 'sh $1 reload' _ {} \;
    fi
}

case $1 in
    "reload")
        plugin_firewall_init
        plugin_firewall_reload
    ;;

    *)
        echo "plugin_firewall: not support cmd: $1"
    ;;
esac

