#!/bin/sh /etc/rc.common

START=97

USE_PROCD=1
NAME=mipctld
PROG=/usr/sbin/${NAME}

start_service() {
    procd_open_instance
    procd_set_param command ${PROG}
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger mipctl_user
}

reload_service() {
    start
    ubus call mipctl reload
}
