#!/bin/sh
#
# Copyright (c) 2015-2016, The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

iptables -C FORWARD -m physdev --physdev-is-bridged -j ACCEPT 2>/dev/null || {
    iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
}

disable_ipv6=$(uci -q get firewall.@defaults[0].disable_ipv6)
if [ "$disable_ipv6" = "1" ]; then
    ip6tables -D FORWARD -m physdev --physdev-is-bridged -j ACCEPT
else
    ip6tables -C FORWARD -m physdev --physdev-is-bridged -j ACCEPT 2>/dev/null || {
        ip6tables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
    }
fi

return 0

